name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_BEACH_08AE29C0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
        env:
            # Only required for localhost
            NEXTAUTH_URL: 'http://localhost:4002'
  
            # You can use openssl to generate a random 32 character key: openssl rand -base64 32
            NEXTAUTH_SECRET: 'rZTFtfNuSMajLnfFrWT2PZ3lX8WZv7W/Xs2H8hkEY6g='
            
            # SMTP / Email settings 
            SMTP_HOST:
            SMTP_PORT:
            SMTP_USER:
            SMTP_PASSWORD:
            SMTP_FROM:
  
            # If you are using Docker, you can retrieve the values from: docker-compose.yml
            DATABASE_URL: 'postgresql://testAzure:Yashdev@123@mydatabase010.postgres.database.azure.com:5432/postgres?sslmode=require'
  
            APP_URL: 'http://localhost:4002'
  
            SVIX_URL: 'https://api.eu.svix.com'
            SVIX_API_KEY:
  
            GITHUB_CLIENT_ID:
            GITHUB_CLIENT_SECRET:
  
            GOOGLE_CLIENT_ID:
            GOOGLE_CLIENT_SECRET:
  
            RETRACED_URL:
            RETRACED_API_KEY:
            RETRACED_PROJECT_ID:
  
            # Hide landing page and redirect to login page
            HIDE_LANDING_PAGE: false
  
            # SSO groups can be prefixed with this identifier in order to avoid conflicts with other groups.
            # For example boxyhq-admin would be resolved to admin, boxyhq-member would be resolved to member, etc.
            GROUP_PREFIX: 'boxyhq-'
  
            # Users will need to confirm their email before accessing the app feature
            CONFIRM_EMAIL: false
  
            # Disable non-business email signup
            DISABLE_NON_BUSINESS_EMAIL_SIGNUP: false
  
            # Mixpanel
            NEXT_PUBLIC_MIXPANEL_TOKEN:
  
            # Jackson
            JACKSON_URL: 'http://localhost:5225'
            JACKSON_API_KEY: 'secret'
            JACKSON_PRODUCT_ID: 'boxyhq'
            JACKSON_WEBHOOK_SECRET: 'your-webhook-secret'
  
            # Enable Auth providers (comma separated)
            # Supported providers: github, google, saml, email, credentials, idp-initiated
            AUTH_PROVIDERS:
  
            # OpenTelemetry
            OTEL_EXPORTER_OTLP_METRICS_ENDPOINT:
            OTEL_EXPORTER_OTLP_METRICS_HEADERS:
            OTEL_EXPORTER_OTLP_METRICS_PROTOCOL: 'grpc'
            OTEL_EXPORTER_DEBUG: true
            OTEL_PREFIX: 'boxyhq.saas'
  
            NEXT_PUBLIC_TERMS_URL: '/terms'
            NEXT_PUBLIC_PRIVACY_URL: '/privacy'
  
            NEXT_PUBLIC_DARK_MODE: false
  
            # Team feature
            FEATURE_TEAM_SSO: false
            FEATURE_TEAM_DSYNC: false
            FEATURE_TEAM_AUDIT_LOG: false
            FEATURE_TEAM_WEBHOOK: false
            FEATURE_TEAM_API_KEY: false
            FEATURE_TEAM_DELETION: false
            FEATURE_TEAM_PAYMENTS: false
  
            # Google reCAPTCHA
            RECAPTCHA_SITE_KEY:
            RECAPTCHA_SECRET_KEY:
  
            # Decide which session strategy (jwt or database) to use with NextAuth
            NEXTAUTH_SESSION_STRATEGY: 'jwt'
  
  
  
  
            # Max login attempts before account is locked
            MAX_LOGIN_ATTEMPTS: 5
  
            # Set this to receive Slack notifications, https://hooks.slack.com/services/xxx/xxx/xxx
            SLACK_WEBHOOK_URL:
  
            # Stripe
            STRIPE_SECRET_KEY:
            STRIPE_WEBHOOK_SECRET:
  
            # Support URL
            NEXT_PUBLIC_SUPPORT_URL:
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_BEACH_08AE29C0F }}
          action: "close"
